-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES TABLE
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  is_admin boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, is_admin)
  values (new.id, false);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user signup
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. PROJECT TABLE
create table if not exists public.project (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  slug text not null unique,
  status text default 'ready'::text, -- 'ready', 'published', 'hidden'
  display_order integer default 0,
  contents jsonb default '{}'::jsonb
);

-- Enable RLS
alter table public.project enable row level security;

-- Policies
create policy "Published projects are viewable by everyone."
  on public.project for select
  using ( status = 'published' or (select is_admin from profiles where id = auth.uid()) = true );

create policy "Admins can insert projects."
  on public.project for insert
  with check ( (select is_admin from profiles where id = auth.uid()) = true );

create policy "Admins can update projects."
  on public.project for update
  using ( (select is_admin from profiles where id = auth.uid()) = true );

create policy "Admins can delete projects."
  on public.project for delete
  using ( (select is_admin from profiles where id = auth.uid()) = true );


-- 3. CONFIG TABLE (for About page, etc.)
create table if not exists public.config (
  id text primary key, -- e.g. 'about'
  content jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.config enable row level security;

-- Policies
create policy "Config is viewable by everyone."
  on public.config for select
  using ( true );

create policy "Admins can insert config."
  on public.config for insert
  with check ( (select is_admin from profiles where id = auth.uid()) = true );

create policy "Admins can update config."
  on public.config for update
  using ( (select is_admin from profiles where id = auth.uid()) = true );

create policy "Admins can delete config."
  on public.config for delete
  using ( (select is_admin from profiles where id = auth.uid()) = true );

-- Initial Seed for Config
insert into public.config (id, content)
values ('about', '{}'::jsonb)
on conflict (id) do nothing;

